# Generated by Django 4.0.4 on 2022-05-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
